[project]
name = "holiday-gift-savior"
version = "1.0.0"
description = "Goggle ADK based AI-Agentic Demo project for Kaggle Capstone Project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
